module.exports = Object.freeze({
  GET_GAME_DATA: 'GET_GAME_DATA',
  GET_LIVE_GAMES: 'GET_LIVE_GAMES',
  SET_PRESENTED_TEAM: 'SET_PRESENTED_TEAM',
  OPEN_MODAL: 'OPEN_MODAL',
  CLOSE_MODAL: 'CLOSE_MODAL',
  SET_STATS_VIEW: 'SET_STATS_VIEW',
  SET_STATS_TABS_CONTENT: 'SET_STATS_TABS_CONTENT',
  SET_PLAYER_TABS_CONTENT: 'SET_PLAYER_TABS_CONTENT',
  SET_PLAYER_DATA: 'SET_PLAYER_DATA',
  CLOSE_LIVE_GAMES: 'CLOSE_LIVE_GAMES',
});
